### ISSUE TITLE
Signature is not updated even though manifest changes

### ISSUE THREAD

**Issue by florian-bd** [zhenyong/webpack-stable-module-id-and-hash#13]
I use webpack-stable-module-id-and-hash and inline-manifest-webpack-plugin.
I have a file which references a bunch of bundles. In this file webpack injects the right code to find the bundle signatures in the manifest.

Now in my latest release, I created a new bundle, which changed the manifest. Webpack injected a new index in the file referencing bundles.

But the signature was not updated. I guess maybe it's because the plugin generates the content before webpack injects the index, so in that sense it is exactly the same file.

Any idea if this issue can be solved?

Note: I had the same issue when I updated the config of CommonsChunkPlugin. It adds a global variable at the beginning of each bundle. I need to update the name of the variable, and same issue, it did not update the signature. This was solved by purging the cache in the CDN.
In that case it is every time we add a new bundle which is not acceptable for long term caching

**Comment by florian-bd** [comment]
Actually what I need is webpack to not change these indexes when I add new bundles. Otherwise it would mean that the signature of files using require.ensure would change even though the source code has not changed

**Comment by zhenyong** [comment]
@florian-bd 
Which version of webpack?
I will take a look「inline-manifest-webpack-plugin」later, and see what I can do.

**Comment by florian-bd** [comment]
Webpack 1.13.2
But I don't think this is related to webpack-stable-module-id-and-hash. I mean it makes sense that the signature is not updated. Webpack should be smarter and not change the indexes. I will post something on stackoverflow if I don't manage to find anything

**Comment by florian-bd** [comment]
To be more precise:
I need the chunk ids to remain the same after each build, even if I add new chunks. I need to make some research about that.
Probably related to OccurrenceOrderPlugin that I use.
You can close this issue :)

**Comment by florian-bd** [comment]
Ok I realized that this plugin is also about having stable ids. My bad!
So the only problem is probably that I use OccurrenceOrderPlugin?

**Comment by florian-bd** [comment]
Ha but it stable chunk ids that I want

**Comment by zhenyong** [comment]
Yeah! Do not use this plugin with *OccurrenceOrderPlugin*, use this plugin in **Production** stage and *OccurrenceOrderPlugin* in **Development** stage.

**Comment by florian-bd** [comment]
Ok but still I need to have stable chunk IDs.
For that, the only solution I have found is to use the recordsPath.
Then as I add or delete new chunks, the other chunks IDs are untouched.
It would be super nice if this plugin could handle that as well.
Thank you for your quick answers.
