### ISSUE TITLE
Module Id is not stable in theory

### ISSUE THREAD

**Issue by zhenyong** [zhenyong/webpack-stable-module-id-and-hash#3]
Once you try to make module id (hash decimal) shorter，it must cause that `One module Id depend to another`

Suppose that we try to make shoter module ID and default take first char in hash to be module id, if next one meet collision then pick first 2.

```
xx/a.js  --hash-->  A1DE --gen module id--> 65
xx/b.js --hash-->  A2CB --gen module id--> 6502
```

If we remove `require(a.js)` then:

```
xx/b.js --hash-->  A2CB --gen module id--> 65
```

Module ID of b is **NOT** stable.

@jampy  
[Pull Requests · zhenyong/webpack-stable-module-id-and-hash](https://github.com/zhenyong/webpack-stable-module-id-and-hash/pulls) may kill 99.9% (maybe) collision and make module id really stable.

Whatever way we try to kill collision, if we dont use the original full hash (decimal) to be module ID, it cant make sense in theroy.

Let me think think!

**Comment by jampy** [comment]
#1 really does make the module ID absolutely stable.

For me the hash solution completely makes sense.

**Comment by zhenyong** [comment]
@jampy You are my first PR. Thanks! ^_^
